### ISSUE TITLE
Other Unsuitable Pi Models

### ISSUE THREAD

**Issue by ikirker** [EPCCed/wee_archlet#2]
You *may* want to add some extras to the list of various Pi-types: there are also Pi Zeros and Zero Ws. The Zero doesn't have any network interfaces built-in, and the Ws only have wifi, so neither is particularly suitable for this.

(There's also the Pi module + IO board, but they're not that common and are much more expensive than normal Pis.)

**Comment by agngrant** [comment]
Thanks for the suggestion - information has now been added to the instructions (commit https://github.com/EPCCed/wee_archlet/commit/22da1a5a3aaa43b49be615599fa40572afbfc47c).
